import React, { useState, useEffect, useCallback } from 'react';
import './DeviceActionsModal.css';
import { X, Send, Save, Trash2, Plus } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { fetchDeviceTsl, fetchDeviceDecodeConfig, saveDeviceDecodeConfig } from '../../services/api';
import { getTemplateCommandsForModel } from '../../constants/downlinkTemplates';

const DeviceActionsModal = ({ type, device, onClose, onSave, onSend }) => {
  const { credentials, token } = useAuth();
  const [name, setName] = useState(device?.name || '');
  const [downlinks, setDownlinks] = useState(() => [{ name: '', hex: '' }]);

  const persistDownlinks = useCallback(
    async (nextList) => {
      if (!device?.deviceId) return;
      const storageKey = `downlinks_${device.deviceId}`;
      const normalized = (Array.isArray(nextList) ? nextList : [])
        .map((d) => ({
          name: String(d?.name || '').trim(),
          hex: String(d?.hex || '').trim().replace(/\s/g, '').toLowerCase().replace(/^0x/, ''),
        }))
        .filter((d) => d.name && d.hex);
      localStorage.setItem(storageKey, JSON.stringify(normalized));
      try {
        const cfg = await fetchDeviceDecodeConfig(device.deviceId);
        await saveDeviceDecodeConfig(device.deviceId, {
          decoderScript: cfg.decoderScript || '',
          channel: cfg.channel || '',
          downlinks: normalized,
        });
      } catch (e) {
        console.warn('[DeviceActionsModal] Persistencia servidor downlinks:', e.message);
      }
    },
    [device?.deviceId]
  );

  useEffect(() => {
    if (!device?.deviceId || type !== 'downlink') return;
    let cancelled = false;
    (async () => {
      const storageKey = `downlinks_${device.deviceId}`;
      let decodeCfg = null;
      let base = [];
      try {
        decodeCfg = await fetchDeviceDecodeConfig(device.deviceId);
        if (Array.isArray(decodeCfg.downlinks) && decodeCfg.downlinks.length > 0) {
          base = decodeCfg.downlinks.filter((d) => d && d.name && d.hex);
        }
      } catch {
        decodeCfg = null;
      }
      if (base.length === 0) {
        try {
          const raw = localStorage.getItem(storageKey);
          const parsed = raw ? JSON.parse(raw) : [];
          base = Array.isArray(parsed) ? parsed.filter((d) => d && d.name && d.hex) : [];
        } catch {
          base = [];
        }
      }

      const merged = [...base];
      const seen = new Set(merged.map((cmd) => String(cmd.hex || '').trim().toLowerCase()).filter(Boolean));

      const modelTemplates = getTemplateCommandsForModel(device.model || '').map((cmd) => ({
        ...cmd,
        autoGenerated: true,
      }));

      let serviceTemplates = [];
      try {
        const tslResp = await fetchDeviceTsl(device.deviceId, credentials, token);
        const services = tslResp.data?.data?.services || tslResp.data?.services || tslResp.services || [];
        if (Array.isArray(services)) {
          serviceTemplates = services
            .filter((s) => s?.id)
            .map((s) => ({
              name: `${s.name || s.id} (Service)`,
              hex: s.id,
              autoGenerated: true,
            }));
        }
      } catch (err) {
        console.warn('[DeviceActionsModal] Unable to auto-load TSL services:', err.message);
      }

      for (const cmd of [...modelTemplates, ...serviceTemplates]) {
        const key = String(cmd.hex || '').trim().toLowerCase();
        if (!key || seen.has(key)) continue;
        merged.push(cmd);
        seen.add(key);
      }

      const normalized = merged.length > 0 ? merged : [{ name: '', hex: '' }];
      if (cancelled) return;
      setDownlinks(normalized);
      const toStore = normalized.filter((d) => d.name && d.hex);
      localStorage.setItem(storageKey, JSON.stringify(toStore));
      if (toStore.length > 0) {
        try {
          const cfg = decodeCfg || (await fetchDeviceDecodeConfig(device.deviceId));
          await saveDeviceDecodeConfig(device.deviceId, {
            decoderScript: cfg.decoderScript || '',
            channel: cfg.channel || '',
            downlinks: toStore,
          });
        } catch (e) {
          console.warn('[DeviceActionsModal] Sync downlinks al servidor:', e.message);
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [type, device?.deviceId, device?.model, credentials, token]);

  const handleEdit = (e) => {
    e.preventDefault();
    if (name.trim()) {
      onSave(device.deviceId, name.trim());
    }
  };

  const addDownlinkRow = () => {
    const newDownlinks = [...downlinks, { name: '', hex: '' }];
    setDownlinks(newDownlinks);
    void persistDownlinks(newDownlinks.filter((d) => d.name && d.hex));
  };

  const updateDownlinkRow = (index, field, value) => {
    const newDownlinks = [...downlinks];
    newDownlinks[index][field] = value;
    setDownlinks(newDownlinks);
    void persistDownlinks(newDownlinks);
  };

  const removeDownlinkRow = (index) => {
    const newDownlinks = downlinks.filter((_, i) => i !== index);
    setDownlinks(newDownlinks);
    void persistDownlinks(newDownlinks);
  };

  return (
    <div className="modal-overlay" role="presentation">
      <div
        className={`modal-content glass card${type === 'downlink' ? ' device-actions-modal--downlink' : ''}`}
        role="dialog"
        aria-modal="true"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-header">
          <h2>{type === 'edit' ? 'Editar Dispositivo' : `Downlink: ${device.name || device.sn}`}</h2>
          <button className="btn-icon" onClick={onClose}><X size={20} /></button>
        </div>

        {type === 'edit' ? (
          <form onSubmit={handleEdit} className="modal-body">
            <div className="form-group">
              <label>Nombre del Dispositivo</label>
              <input 
                type="text" 
                value={name} 
                onChange={e => setName(e.target.value)}
                className="glass"
                placeholder="Ingresa el nombre..."
                autoFocus
              />
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-secondary" onClick={onClose}>Cancelar</button>
              <button type="submit" className="btn btn-primary"><Save size={18} /> Guardar Cambios</button>
            </div>
          </form>
        ) : (
          <div className="modal-body">
            <div className="downlink-description">
              Comandos hex (y servicios TSL) alineados con la plantilla del dispositivo; se guardan en el servidor y en
              este navegador.
            </div>
            <div className="downlink-list">
              {downlinks.map((dl, index) => (
                <div key={index} className="downlink-row glass">
                  <div className="row-inputs">
                    <input 
                      type="text" 
                      placeholder="Nombre (ej. Abrir)" 
                      value={dl.name}
                      onChange={e => updateDownlinkRow(index, 'name', e.target.value)}
                    />
                    <input 
                      type="text" 
                      placeholder="Hex o Service ID (ej. ff01 / reboot)" 
                      value={dl.hex}
                      onChange={e => updateDownlinkRow(index, 'hex', e.target.value)}
                    />
                  </div>
                  <div className="row-actions">
                    <button 
                      className="btn-icon send" 
                      onClick={() => onSend(device.deviceId, dl.hex, dl.name)} 
                      title="Enviar"
                      disabled={!dl.hex}
                    >
                      <Send size={16} />
                    </button>
                    <button className="btn-icon delete" onClick={() => removeDownlinkRow(index)} title="Eliminar">
                      <Trash2 size={16} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
            
            <button className="btn btn-secondary add-btn" onClick={addDownlinkRow}>
              <Plus size={16} /> Añadir Downlink
            </button>
            
            <div className="modal-footer">
              <button className="btn btn-primary" onClick={onClose}>Cerrar</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default DeviceActionsModal;
