import React, { useState, useEffect, useRef, useCallback } from 'react';
import './DeviceActionsModal.css';
import { X, Send, Save, Trash2, Plus } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { fetchDeviceTsl, putDeviceDownlinkPresets } from '../../services/api';
import { getTemplateCommandsForModel } from '../../constants/downlinkTemplates';
import {
  readDownlinksFromLocalStorage,
  downlinksLocalStorageKey,
  getStoredTemplateIdForDevice,
  getDeviceTemplateById,
  normalizeTelemetryLabelHints,
  primeDeviceSharedPresetsFromDeviceRows,
} from '../../services/deviceTemplates';

const DeviceActionsModal = ({ type, device, onClose, onSave, onSend }) => {
  const { credentials, token } = useAuth();
  const downlinkServerTimerRef = useRef(null);

  const persistDownlinksToServer = useCallback(async (deviceId) => {
    if (!deviceId) return;
    try {
      const raw = readDownlinksFromLocalStorage(deviceId);
      const useful = (Array.isArray(raw) ? raw : []).filter(
        (d) => String(d?.name || '').trim() && String(d?.hex || '').trim()
      );
      const tid = getStoredTemplateIdForDevice(deviceId);
      const tpl = tid ? getDeviceTemplateById(tid) : null;
      const telemetryLabels = tpl ? normalizeTelemetryLabelHints(tpl.telemetryLabels) : {};
      await putDeviceDownlinkPresets(deviceId, {
        downlinks: useful,
        catalogTemplateId: tid || null,
        telemetryLabels,
      });
      primeDeviceSharedPresetsFromDeviceRows([
        {
          deviceId,
          deviceSharedPresets: {
            downlinks: useful,
            catalogTemplateId: tid || null,
            telemetryLabels,
          },
        },
      ]);
    } catch (e) {
      console.warn('[DeviceActionsModal] presets servidor:', e?.message || e);
    }
  }, []);

  const scheduleDownlinksServerSave = useCallback(
    (deviceId) => {
      if (!deviceId) return;
      if (downlinkServerTimerRef.current) clearTimeout(downlinkServerTimerRef.current);
      downlinkServerTimerRef.current = setTimeout(() => {
        downlinkServerTimerRef.current = null;
        persistDownlinksToServer(deviceId);
      }, 650);
    },
    [persistDownlinksToServer]
  );
  const [name, setName] = useState(device?.name || '');
  const [tag, setTag] = useState(device?.tag != null ? String(device.tag) : '');
  const [downlinks, setDownlinks] = useState(() => {
    const list = readDownlinksFromLocalStorage(device?.deviceId);
    return list.length ? list : [{ name: '', hex: '' }];
  });

  useEffect(() => {
    const list = readDownlinksFromLocalStorage(device?.deviceId);
    const next = list.length ? list : [{ name: '', hex: '' }];
    queueMicrotask(() => setDownlinks(next));
  }, [device?.deviceId]);

  useEffect(() => {
    setName(device?.name || '');
    setTag(device?.tag != null ? String(device.tag) : '');
  }, [device?.deviceId, device?.name, device?.tag]);

  useEffect(() => {
    const seedAutoCommands = async () => {
      if (!device?.deviceId) return;
      const storageKey = downlinksLocalStorageKey(device.deviceId);
      const saved = readDownlinksFromLocalStorage(device.deviceId);

      const modelTemplates = getTemplateCommandsForModel(device.model || '').map(cmd => ({
        ...cmd,
        autoGenerated: true,
      }));

      let serviceTemplates = [];
      try {
        const tslResp = await fetchDeviceTsl(device.deviceId, credentials, token);
        const services = tslResp.data?.data?.services || tslResp.data?.services || tslResp.services || [];
        if (Array.isArray(services)) {
          serviceTemplates = services
            .filter(s => s?.id)
            .map(s => ({
              name: `${s.name || s.id} (Service)`,
              hex: s.id,
              autoGenerated: true,
            }));
        }
      } catch (err) {
        console.warn('[DeviceActionsModal] Unable to auto-load TSL services:', err.message);
      }

      const merged = [...saved];
      const seen = new Set(
        merged
          .map(cmd => String(cmd.hex || '').trim().toLowerCase())
          .filter(Boolean)
      );

      for (const cmd of [...modelTemplates, ...serviceTemplates]) {
        const key = String(cmd.hex || '').trim().toLowerCase();
        if (!key || seen.has(key)) continue;
        merged.push(cmd);
        seen.add(key);
      }

      const normalized = merged.length > 0 ? merged : [{ name: '', hex: '' }];
      localStorage.setItem(storageKey, JSON.stringify(normalized));
      setDownlinks(normalized);
      scheduleDownlinksServerSave(device.deviceId);
    };

    if (type === 'downlink') seedAutoCommands();
  }, [type, device?.deviceId, device?.model, credentials, token, scheduleDownlinksServerSave]);

  const handleEdit = (e) => {
    e.preventDefault();
    if (name.trim()) {
      onSave(device.deviceId, name.trim(), tag.trim());
    }
  };

  const addDownlinkRow = () => {
    const next = [...downlinks, { name: '', hex: '' }];
    setDownlinks(next);
    localStorage.setItem(downlinksLocalStorageKey(device?.deviceId), JSON.stringify(next));
    scheduleDownlinksServerSave(device?.deviceId);
  };

  const updateDownlinkRow = (index, field, value) => {
    const newDownlinks = [...downlinks];
    newDownlinks[index][field] = value;
    setDownlinks(newDownlinks);
    localStorage.setItem(downlinksLocalStorageKey(device?.deviceId), JSON.stringify(newDownlinks));
    scheduleDownlinksServerSave(device?.deviceId);
  };

  const removeDownlinkRow = (index) => {
    const newDownlinks = downlinks.filter((_, i) => i !== index);
    setDownlinks(newDownlinks);
    localStorage.setItem(downlinksLocalStorageKey(device?.deviceId), JSON.stringify(newDownlinks));
    scheduleDownlinksServerSave(device?.deviceId);
  };

  const [sendingRow, setSendingRow] = useState(null);
  const [sentFlashRow, setSentFlashRow] = useState(null);

  const handleSendRow = async (index, hex, name) => {
    const payload = String(hex || '').trim();
    if (!payload || sendingRow !== null || !onSend) return;
    setSendingRow(index);
    try {
      await Promise.resolve(onSend(device.deviceId, payload, name));
      setSentFlashRow(index);
      window.setTimeout(() => {
        setSentFlashRow((cur) => (cur === index ? null : cur));
      }, 520);
    } finally {
      setSendingRow(null);
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className={`modal-content glass card${type === 'downlink' ? ' device-actions-modal--downlink' : ''}`}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-header">
          <h2>{type === 'edit' ? 'Editar Dispositivo' : `Downlink: ${device.name || device.sn}`}</h2>
          <button className="btn-icon" onClick={onClose}><X size={20} /></button>
        </div>

        {type === 'edit' ? (
          <form onSubmit={handleEdit} className="modal-body">
            <div className="form-group">
              <label htmlFor="device-edit-name">Nombre del dispositivo</label>
              <input
                id="device-edit-name"
                name="device-edit-name"
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="glass"
                placeholder="Ingresa el nombre…"
                autoFocus
              />
            </div>
            <div className="form-group">
              <label htmlFor="device-edit-tag">Etiqueta (identificación)</label>
              <input
                id="device-edit-tag"
                name="device-edit-tag"
                type="text"
                value={tag}
                onChange={(e) => setTag(e.target.value)}
                className="glass"
                placeholder="Opcional: referencia interna, ubicación, etc."
                maxLength={128}
              />
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-secondary" onClick={onClose}>Cancelar</button>
              <button type="submit" className="btn btn-primary"><Save size={18} /> Guardar Cambios</button>
            </div>
          </form>
        ) : (
          <div className="modal-body">
            <div className="downlink-list">
              {downlinks.map((dl, index) => (
                <div key={index} className="downlink-row glass">
                  <div className="row-inputs">
                    <input 
                      type="text" 
                      placeholder="Nombre (ej. Abrir)" 
                      value={dl.name}
                      onChange={e => updateDownlinkRow(index, 'name', e.target.value)}
                    />
                    <input 
                      type="text" 
                      placeholder="Hex o Service ID (ej. ff01 / reboot)" 
                      value={dl.hex}
                      onChange={e => updateDownlinkRow(index, 'hex', e.target.value)}
                    />
                  </div>
                  <div className="row-actions">
                    <button
                      type="button"
                      className={[
                        'downlink-action-btn',
                        'downlink-action-btn--send',
                        sendingRow === index ? 'is-sending' : '',
                        sentFlashRow === index ? 'is-sent' : '',
                      ]
                        .filter(Boolean)
                        .join(' ')}
                      onClick={() => handleSendRow(index, dl.hex, dl.name)}
                      title={sendingRow === index ? 'Enviando…' : 'Enviar downlink'}
                      aria-label={sendingRow === index ? 'Enviando downlink' : `Enviar ${dl.name || 'comando'}`}
                      disabled={!String(dl.hex || '').trim() || sendingRow !== null}
                    >
                      <span className="downlink-action-btn__icon" aria-hidden>
                        <Send size={17} strokeWidth={2.25} />
                      </span>
                    </button>
                    <button
                      type="button"
                      className="downlink-action-btn downlink-action-btn--delete"
                      onClick={() => removeDownlinkRow(index)}
                      title="Eliminar comando"
                      aria-label={`Eliminar ${dl.name || 'comando'}`}
                      disabled={sendingRow !== null}
                    >
                      <span className="downlink-action-btn__icon" aria-hidden>
                        <Trash2 size={17} strokeWidth={2.25} />
                      </span>
                    </button>
                  </div>
                </div>
              ))}
            </div>
            
            <button className="btn btn-secondary add-btn" onClick={addDownlinkRow}>
              <Plus size={16} /> Añadir Downlink
            </button>
            
            <div className="modal-footer">
              <button className="btn btn-primary" onClick={onClose}>Cerrar</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default DeviceActionsModal;
